### ISSUE TITLE
Not working on windows phone

### ISSUE THREAD

**Issue by mauricionr** [lonekorean/diff-cam-feed#2]

**Comment by lonekorean** [comment]
Which browser are you seeing on Windows Phone? IE11 doesn't support getUserMedia(), but Edge should.

**Comment by mauricionr** [comment]
I'm using windows phone with windows 10 and the browser is Edge.

The application request camera access but after that nothing happens.

I've made a few [changes](https://github.com/netcombr/diff-cam-feed) to check it out what is going on

![image](https://cloud.githubusercontent.com/assets/2263551/17083379/be5b08e8-5175-11e6-9656-7a76ad4737db.png)

but no alert on windows phone with the error

on my old android phone i've got an alert with an error #4

**Comment by lonekorean** [comment]
Sometimes these things fail silently, so you may not get any errors to catch.

Do you have a repo somewhere where I can see the code?

**Comment by mauricionr** [comment]
@lonekorean check it out the code here [Diff Cam Feed](https://github.com/netcombr/diff-cam-feed)

**Comment by mauricionr** [comment]
I've tested with Opera on Windows Phone 10 and Android 2.3.6 #4 both got the same error, diffrent from #4 

![wp_ss_20160724_0002 1](https://cloud.githubusercontent.com/assets/2263551/17085904/94c9774a-51ba-11e6-9f04-babcd1359dfb.png)

**Comment by lonekorean** [comment]
I also tested my diff-cam-feed in Opera on desktop and it's not working, so that's a bummer. Edge doesn't work either, it's giving me a MediaStreamError "SourceUnavailableError". I could swear it previously worked fine.

This will require some investigation.

**Comment by mauricionr** [comment]
On my windows 10 desktop working normally on edge, looks like only happen on windows phone 10 using edge.
