### ISSUE TITLE
Not working on android version 2.3.6

### ISSUE THREAD

**Issue by mauricionr** [lonekorean/diff-cam-feed#4]
I'm trying to figure out why this is happening.

![whatsapp-image-20160724 1](https://cloud.githubusercontent.com/assets/2263551/17083407/5e2ab3d2-5176-11e6-8f3b-d347f051cb13.jpeg)

![whatsapp-image-20160724](https://cloud.githubusercontent.com/assets/2263551/17083408/6294fb80-5176-11e6-9421-060b76b8f380.jpeg)

**Comment by lonekorean** [comment]
Which browser are you using? It won't work in the stock Android browser for versions < 5.x. I recommend installing Firefox if you can. You could try Chrome, but in my experience it dies after a couple minutes.

It's weird that it says DiffCamEngine is not defined. That's not the error I would expect...
