### ISSUE TITLE
Not working on Opera(Desktop/Mobile) => MediaStreamError "SourceUnavailableError"

### ISSUE THREAD

**Issue by mauricionr** [lonekorean/diff-cam-feed#5]
As you said in this issue #2, i opened this issue to track this problem later!

Awsome project @lonekorean!

**Comment by mauricionr** [comment]
I've tested in opera on desktop and it works fine, wich version are you using?

Maybe a limitation by version.

**Comment by lonekorean** [comment]
On 38 as well. Just tried it again and it's working fine. Weird.
